var searchData=
[
  ['q_5fprivate_5fslot',['Q_PRIVATE_SLOT',['../class_qext_serial_port.html#a37a861b3982bbe201d178d9332d64407',1,'QextSerialPort']]],
  ['q_5fptr',['q_ptr',['../class_qext_serial_enumerator_private.html#abaef1d80b864752791915a06720dc8a2',1,'QextSerialEnumeratorPrivate::q_ptr()'],['../class_qext_serial_port_private.html#ac1a6c45f7c3621d5f926d5250cdac194',1,'QextSerialPortPrivate::q_ptr()'],['../class_qext_win_event_notifier_private.html#ad3a8d06a8888d236f65867f31ad6c8df',1,'QextWinEventNotifierPrivate::q_ptr()']]],
  ['qesp_5fportability_5fwarning',['QESP_PORTABILITY_WARNING',['../qextserialport__global_8h.html#a89e7b6ddd27b54d9eab305c7626b228b',1,'qextserialport_global.h']]],
  ['qesp_5fwarning',['QESP_WARNING',['../qextserialport__global_8h.html#ab20a5827010048f4f34928cafcf1931b',1,'qextserialport_global.h']]],
  ['qextportinfo',['QextPortInfo',['../struct_qext_port_info.html',1,'']]],
  ['qextreadbuffer',['QextReadBuffer',['../class_qext_read_buffer.html',1,'QextReadBuffer'],['../class_qext_read_buffer.html#a7ae54f95b884a2ac522c7f27a9e1eb5d',1,'QextReadBuffer::QextReadBuffer()']]],
  ['qextserialenumerator',['QextSerialEnumerator',['../class_qext_serial_enumerator.html',1,'QextSerialEnumerator'],['../class_qext_serial_enumerator.html#a3c6f9fc4b5835d63197caa424dc6703e',1,'QextSerialEnumerator::QextSerialEnumerator()']]],
  ['qextserialenumerator_2ecpp',['qextserialenumerator.cpp',['../qextserialenumerator_8cpp.html',1,'']]],
  ['qextserialenumerator_2eh',['qextserialenumerator.h',['../qextserialenumerator_8h.html',1,'']]],
  ['qextserialenumerator_5flinux_2ecpp',['qextserialenumerator_linux.cpp',['../qextserialenumerator__linux_8cpp.html',1,'']]],
  ['qextserialenumerator_5fosx_2ecpp',['qextserialenumerator_osx.cpp',['../qextserialenumerator__osx_8cpp.html',1,'']]],
  ['qextserialenumerator_5fp_2eh',['qextserialenumerator_p.h',['../qextserialenumerator__p_8h.html',1,'']]],
  ['qextserialenumerator_5funix_2ecpp',['qextserialenumerator_unix.cpp',['../qextserialenumerator__unix_8cpp.html',1,'']]],
  ['qextserialenumerator_5fwin_2ecpp',['qextserialenumerator_win.cpp',['../qextserialenumerator__win_8cpp.html',1,'']]],
  ['qextserialenumeratorprivate',['QextSerialEnumeratorPrivate',['../class_qext_serial_enumerator_private.html',1,'QextSerialEnumeratorPrivate'],['../class_qext_serial_enumerator_private.html#a68080efc6f1bf4ba3d61354caa6b1f77',1,'QextSerialEnumeratorPrivate::QextSerialEnumeratorPrivate()']]],
  ['qextserialport',['QextSerialPort',['../class_qext_serial_port.html',1,'QextSerialPort'],['../class_qext_serial_port.html#af36bd1a07fc25c3874cbba5a4a1d6b02',1,'QextSerialPort::QextSerialPort(QueryMode mode=EventDriven, QObject *parent=0)'],['../class_qext_serial_port.html#ab8e7dd61c9b064b55d4c609ae1f2afcb',1,'QextSerialPort::QextSerialPort(const QString &amp;name, QueryMode mode=EventDriven, QObject *parent=0)'],['../class_qext_serial_port.html#a7ddaffdbbb507477fd4f4224dcbe21a4',1,'QextSerialPort::QextSerialPort(const PortSettings &amp;s, QueryMode mode=EventDriven, QObject *parent=0)'],['../class_qext_serial_port.html#aff4f0246637293ba6751a5993a645b20',1,'QextSerialPort::QextSerialPort(const QString &amp;name, const PortSettings &amp;s, QueryMode mode=EventDriven, QObject *parent=0)']]],
  ['qextserialport_2ecpp',['qextserialport.cpp',['../qextserialport_8cpp.html',1,'']]],
  ['qextserialport_2eh',['qextserialport.h',['../qextserialport_8h.html',1,'']]],
  ['qextserialport_5fexport',['QEXTSERIALPORT_EXPORT',['../qextserialport__global_8h.html#aa3feb167663777e733b50c492c3e3c88',1,'qextserialport_global.h']]],
  ['qextserialport_5fglobal_2eh',['qextserialport_global.h',['../qextserialport__global_8h.html',1,'']]],
  ['qextserialport_5fp_2eh',['qextserialport_p.h',['../qextserialport__p_8h.html',1,'']]],
  ['qextserialport_5funix_2ecpp',['qextserialport_unix.cpp',['../qextserialport__unix_8cpp.html',1,'']]],
  ['qextserialport_5fwin_2ecpp',['qextserialport_win.cpp',['../qextserialport__win_8cpp.html',1,'']]],
  ['qextserialportprivate',['QextSerialPortPrivate',['../class_qext_serial_port_private.html',1,'QextSerialPortPrivate'],['../class_qext_serial_port_private.html#ae40028def454b3b7ceda96590c843561',1,'QextSerialPortPrivate::QextSerialPortPrivate()']]],
  ['qextwineventnotifier',['QextWinEventNotifier',['../class_qext_win_event_notifier.html',1,'QextWinEventNotifier'],['../class_qext_win_event_notifier.html#a848e79bf76496d7d6109b320ba729c33',1,'QextWinEventNotifier::QextWinEventNotifier(QObject *parent=0)'],['../class_qext_win_event_notifier.html#ace16d2f7e52b52f681792e46c2b3bccb',1,'QextWinEventNotifier::QextWinEventNotifier(HANDLE hEvent, QObject *parent=0)']]],
  ['qextwineventnotifier_5fp_2ecpp',['qextwineventnotifier_p.cpp',['../qextwineventnotifier__p_8cpp.html',1,'']]],
  ['qextwineventnotifier_5fp_2eh',['qextwineventnotifier_p.h',['../qextwineventnotifier__p_8h.html',1,'']]],
  ['qextwineventnotifierprivate',['QextWinEventNotifierPrivate',['../class_qext_win_event_notifier_private.html',1,'QextWinEventNotifierPrivate'],['../class_qext_win_event_notifier_private.html#a79477c0c1c05f6ca2f5eb04a576a82b1',1,'QextWinEventNotifierPrivate::QextWinEventNotifierPrivate()']]],
  ['qextwineventnotifierthread',['QextWinEventNotifierThread',['../class_qext_win_event_notifier_thread.html',1,'QextWinEventNotifierThread'],['../class_qext_win_event_notifier_thread.html#a873614e5ee3450a4b2ccc041ba1230ec',1,'QextWinEventNotifierThread::QextWinEventNotifierThread()']]],
  ['qstringtotchar',['QStringToTCHAR',['../qextserialenumerator__win_8cpp.html#a774e4ae0995c78347820121dcd664353',1,'qextserialenumerator_win.cpp']]],
  ['quenewslice',['QueNewSlice',['../class_slice_set.html#af26423763c68f59e2e7963b090578c70',1,'SliceSet']]],
  ['querymode',['queryMode',['../class_qext_serial_port.html#a22867092a82eb015ad6f84fd4ade1073',1,'QextSerialPort::queryMode()'],['../class_qext_serial_port.html#acde21b700d669d9de3fcac157cb38ba0',1,'QextSerialPort::queryMode() const '],['../class_qext_serial_port.html#a6002128d7351ea9a958d6a6d1fc6b9bd',1,'QextSerialPort::QueryMode()']]]
];
